backend:
  name: github
  repo: ScriptGadget/amarillo-tech-meetup # Path to your Github repository
  branch: master # Branch to update
  site_domain: amarillo-tech-meetup.netlify.com # Your Netlify site address if different from host
  media_folder: "img" # Media files will be stored in the repo under images/uploads

collections:
  - name: "blog" # Used in routes, e.g. /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection



